default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST', 'postgres_b') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>
  database: <%= ENV.fetch('DB_NAME', 'system_b_development') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>

development:
  <<: *default

production:
  <<: *default
